### ISSUE TITLE
Something designed to look good in monochrome needed

### ISSUE THREAD

**Issue by DavidGriffith** [cantonbecker/bitcoinpaperwallet#20]
This is nice, but it would be nicer to have some graphics that would make for a good-looking paper wallet printed on a monochrome laser printer.  Got any ideas?

**Comment by cantonbecker** [comment]
Thanks for the reminder. A B&W suitable design that's vector based (not a JPG) is at the top of my list.

**Comment by DavidGriffith** [comment]
Looks like you did it in 657db38f3d068de4cfbc13b8cf6a02466767b9b0 and forgot to mention it here.  Thanks!

**Comment by DavidGriffith** [comment]
Whoops!  It's JPG-based.  Doesn't look like any of the designs are vector-based yet.  Oh well.  Opening again.
